### ISSUE TITLE
how to use command hello with two params?

### ISSUE THREAD

**Issue by qiuqiu3** [sedders123/phial#139]
when i tried command with "!hello 1 2", and bot response Hi 1 2

**Comment by sedders123** [comment]
Sorry for the delayed response. Sorry but it looks like I put a weird corner case in the examples so that file doesn't work without modification, I have now updated them.

The simplest fix is to change `hello` to something else in one of the commands. The below snippet should work.
```python
@slackbot.command('hi <name>')
def hello(name):
    '''Simple command with argument which replies to a message'''
    return Response(text="Hi {0}".format(name), channel=command.channel)


@slackbot.command('hello <name> <from_>')
def hello_from(name, from_):
    '''Simple command with two arguments which replies to a message'''
    return Response(text="Hi {0}, from {1}".format(name, from_),
                    channel=command.channel)
```
The reason this is needed is due to inner workings of phial. When commands are registered their 'patterns' (the strings passed into the command decorator) are converted to regex and added to list. When a slack message is detected phial loops through the list until a match is found which it then executes.

An alternative solution would be to register the more specific commands first
```python
@slackbot.command('hello <name> <from_>')
def hello(name, from_):
    '''Simple command with two arguments which replies to a message'''
    return Response(text="Hi {0}, from {1}".format(name, from_),
                    channel=command.channel)

@slackbot.command('hello <name>')
def hello_from(name):
    '''Simple command with argument which replies to a message'''
    return Response(text="Hi {0}".format(name), channel=command.channel)

```

Sorry for the confusion this caused, when I get some free time (a rarirty) documenting phial is my number one priority. If you have any more questions going forward please just raise another issue and I'll do my best to get back to you in a timely manner

**Comment by sedders123** [comment]
Going to close this now, if the issue persists feel free to reopen
